version: '3.9'

services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    container_name: school_client
    ports: 
     - '5173:5173'
    volumes:
      - /src
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres-data:
  minio_data:

networks:
  net: