FROM node:20-slim
WORKDIR /app
ENV PATH app/node_modules/.bin:$PATH
COPY /frontend/package.json ./
COPY /frontend/package-lock.json ./

RUN npm ci --silent

COPY /frontend .

RUN npm run build

CMD ["npm", "run", "start"]