name: CI

on:
  push:
    branches: [ "master"]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ..;
            cd var/test/school_media/;
            git pull;
            docker compose -f /var/test/school_media/docker-compose.yaml up -d --build;
            docker system prune --all --force;